import Foundation

enum L10n {
    private static let strings: [String: [String: String]] = [
        "en": [
            "app_name": "AfyaHASET",
            "tagline": "Healthcare in Your Palm",
            "about_us": "About Us",
            "activity_logs": "Activity Logs",
            "additional": "Additional",
            "administrator": "Administrator",
            "administrator_dashboard": "Administrator Dashboard",
            "all_users": "All Users",
            "already_have_account": "Already have an account?",
            "appointments": "Appointments",
            "book_online_chat": "Online Chat",
            "archived": "Archived",
            "approved": "Approved",
            "approve": "Approve",
            "articles": "Articles",
            "available": "Available",
            "available_times": "Available Times",
            "basic": "Basic",
            "book_appointment": "Book Appointment",
            "book_visit": "Book Visit",
            "booked": "Booked",
            "bug_report": "Bug Report",
            "buy_medicine": "Buy Medicine",
            "call_support": "Call Support",
            "chat": "Chat",
            "chat_doctor": "Chat Doctor",
            "chat_securely": "Chat Securely",
            "chat_securely_desc": "Real-time chat and private messaging.",
            "close": "Close",
            "cancel": "Cancel",
            "cancel_payment": "Cancel payment",
            "cancel_payment_warning": "Your payment is still being confirmed. Cancel only if you do not want to continue.",
            "keep_waiting": "Keep waiting",
            "cancel_appointment": "Cancel appointment",
            "completed": "Completed",
            "contact": "Contact",
            "delete_account": "Delete Account",
            "doctor": "Doctor",
            "doctor_dashboard": "Doctor Dashboard",
            "doctor_details": "Doctor Details",
            "doctor_verified": "Verified",
            "doctor_awaiting_admin_approval": "Your account is waiting for admin approval. You can use the app, but patients cannot find or book you until an administrator approves your MCT documents.",
            "doctor_pending_admin_badge": "Pending admin approval",
            "error": "Error",
            "success": "Success",
            "login_failed": "Incorrect email or password.",
            "registration_successful": "Registration Successful",
            "registration_failed": "Registration Failed",
            "verify_email_after_registration": "Welcome to HASET. Please check your email and verify your account.",
            "verify_email_before_login": "Please verify your email address before signing in. We sent you a new verification email.",
            "reset_failed": "Reset Failed",
            "update_failed": "Update Failed",
            "booking_successful": "Booking Successful",
            "booking_failed": "Booking Failed",
            "report_sent": "Report Sent",
            "permission_required": "Permission Required",
            "valid_email_required": "Please enter a valid email",
            "password_too_short": "Password must be at least 6 characters",
            "strong_password_required": "Use at least 12 characters with uppercase, lowercase, and a number",
            "password_auth_ok": "Password looks valid",
            "registration_fields_required": "Enter a valid name, email, 9-digit phone number, and a password with at least 12 characters, uppercase, lowercase, and a number.",
            "verification_email_sent": "A verification email has been sent. Please check your inbox and spam folder, then verify your account before signing in.",
            "name_required": "Please enter your name",
            "valid_phone_required": "Please enter a valid phone number",
            "mct_required": "MCT Registration Number is required",
            "nin_required": "NIN is required",
            "valid_nin_required": "Enter a valid 20-digit NIN",
            "nin_document_required": "Upload your NIN as a PDF",
            "mct_certificate_required": "Upload your MCT registration certificate as a PDF",
            "document_pdf_only": "Only PDF documents are accepted",
            "upload_nin_document": "Upload NIN document (PDF)",
            "upload_mct_certificate": "Upload MCT certificate (PDF)",
            "document_upload": "Upload",
            "document_selected": "Selected",
            "hint_mct_reg_no": "Tanzanian Medical Council (MCT) Reg. No. (e.g. MCT3625)",
            "hint_nin": "NIN (20 digits)",
            "doctor_registration_pdf_details_required": "Enter valid details and upload both verification documents as PDF.",
            "uploading_documents": "Uploading documents…",
            "doctor_reg_payment_required": "Pay the doctor registration fee to finish sign-in. You cannot use the app until payment is complete.",
            "login_locked": "Too many failed login attempts. Please try again in %1$d minute(s).",
            "reset_email_sent": "A password reset link has been sent to your email. Please check your inbox and spam folder.",
            "reset_email_not_found": "No account found with this email address. Please check the email or register.",
            "profile_updated_successfully": "Profile updated successfully",
            "describe_issue_first": "Please describe the issue first",
            "report_recorded": "Your report has been recorded for the HASET support team.",
            "select_date_required": "Please select a date",
            "select_time_required": "Please select a time",
            "chat_booking_success": "Appointment booked successfully",
            "appointment_booking_success": "Appointment booked successfully",
            "notifications_permission_message": "AfyaHASET needs notification permission to send you important appointment reminders and welcome messages. Please enable notifications in settings.",
            "location_permission_message": "Please allow location access in iPhone Settings to use nearby hospitals and doctor discovery.",
            "choose_appointment_type": "Choose Appointment Type",
            "dont_have_account": "Don't have an account?",
            "change_password": "Change Password",
            "edit_profile": "Edit Profile",
            "email": "Email",
            "english": "English",
            "find_doctors": "Find Doctors",
            "find_hospital": "Find Hospital",
            "filter_by_specialist": "Filter by Specialist",
            "forgot_password": "Forgot Password?",
            "forgot_password_description": "Enter your email address and we'll send you a link to reset your password.",
            "full_name": "Full Name",
            "general": "General",
            "health_at_hand": "Health at Hand",
            "health_at_hand_desc": "Track appointments & prescriptions.",
            "help_support": "Help and Support",
            "home": "Home",
            "hospitals": "Hospitals",
            "hello": "Hello,",
            "im_administrator": "I'm an Admin",
            "im_doctor": "I'm a Doctor",
            "im_patient": "I'm a Patient",
            "inbox": "Inbox",
            "instant_appointment": "Instant Appointment",
            "kiswahili": "Swahili",
            "language": "Language",
            "location": "Location",
            "location_permission": "Location Access",
            "login": "Login",
            "logout": "Logout",
            "manage_schedule": "Manage Schedule",
            "medical_disclaimer": "Medical Disclaimer",
            "medical_records": "Medical Records",
            "more": "More",
            "my_appointments": "My Appointments",
            "my_prescriptions": "My Prescriptions",
            "patients": "Patients",
            "filter": "Filter",
            "no_prescriptions_message": "Your prescriptions will appear here",
            "prescriptions": "Prescriptions",
            "passwords_do_not_match": "Passwords do not match",
            "password_reset_success": "Password reset successfully. Please sign in.",
            "paste_reset_link": "Paste reset link from email",
            "reset_new_password": "New Password",
            "reset_confirm_password": "Confirm New Password",
            "reset_password_action": "Reset Password",
            "no_appointments_message": "No appointments found",
            "no_messages_message": "No messages yet",
            "next": "Next",
            "nearby_hospitals": "Nearby Hospitals",
            "notification": "Notification",
            "notifications": "Notifications",
            "or": "or",
            "password": "Password",
            "patient": "Patient",
            "patient_dashboard": "Patient Dashboard",
            "payment": "Payment",
            "secure_payment": "Secure Payment",
            "payment_initiated": "Payment initiated. Please complete the transaction on your phone.",
            "preparing_payment": "Processing payment…",
            "payment_session_unavailable": "Secure payment is not ready. Tap Pay Now to retry.",
            "payment_method": "Payment Method",
            "payment_number": "Wallet Number",
            "payment_provider": "Provider",
            "pay_now": "Pay Now",
            "pending": "Pending",
            "decline": "Decline",
            "reschedule": "Reschedule",
            "reschedule_appointment": "Reschedule appointment",
            "start_chat": "Start Chat Now",
            "open_chat": "Chat Now",
            "confirm_appointment_action": "Are you sure you want to update this appointment?",
            "phone": "Phone Number",
            "phone_number": "Phone Number",
            "popular_articles": "Popular Articles",
            "popular_doctors": "Popular Doctors",
            "preferences": "Preferences",
            "privacy_policy": "Privacy Policy",
            "profile": "Profile",
            "published": "Published",
            "quick_access": "Quick Access",
            "recent": "Recent",
            "recent_appointments": "Recent Appointments",
            "register": "Register",
            "remember_me": "Remember me",
            "remember_password": "Remember your password?",
            "role_selection_title": "Select Your Role",
            "save_changes": "Save Changes",
            "schedule_appointment": "Schedule Appointment",
            "schedule_for_future": "Book for a future date and time",
            "select_method": "Select method",
            "select_provider": "Select provider",
            "schedule_overview": "Today's Overview",
            "today_s_overview": "Today's Overview",
            "quick_actions": "Quick Actions & Services",
            "schedule": "Schedule",
            "search": "Search",
            "check_status": "Check Status",
            "select_date": "Select Date",
            "select_time": "Select Time",
            "services": "Services",
            "send_reset_link": "Send Reset Link",
            "settings": "Settings",
            "multi_factor_authentication": "Multi-factor authentication",
            "mfa_enabled_desc": "Extra sign-in protection is enabled",
            "mfa_disabled_desc": "Protect sign-in with an authenticator app",
            "reason_for_visit": "Reason for visit",
            "share_profile": "Share Profile",
            "sign_in": "Sign In",
            "sign_in_here": "Sign Up here",
            "sign_up": "Sign Up",
            "status": "Status",
            "support": "Support",
            "search_articles": "Search articles...",
            "search_doctors": "Search doctors",
            "health_tips": "Health Tips",
            "no_health_tips_found": "No health tips found",
            "no_articles_found": "No articles found",
            "no_comments_yet": "No comments yet",
            "write_comment": "Write a comment...",
            "post_comment": "Post Comment",
            "comments": "Comments",
            "use_date": "Use Date",
            "use_time": "Use Time",
            "consultation_fee": "Consultation Fee",
            "payment_method_label": "Payment method",
            "mobile_money": "Mobile Money",
            "card_payment": "Card Payment",
            "hosted_card_checkout": "Secure hosted card checkout",
            "card_checkout_description": "You will complete payment on the secure gateway page. HASET never collects card details.",
            "card_checkout_opened": "Secure card checkout opened",
            "account_card_number": "Account / card number",
            "terminate": "Terminate",
            "payment_in_progress": "Payment in progress",
            "confirm_prompt_phone": "Please check your phone for the USSD prompt",
            "waiting_payment_confirmation": "Waiting for payment confirmation...",
            "check_phone_complete_payment": "Check your phone to complete the payment.",
            "payment_confirmed": "Payment confirmed successfully!",
            "still_waiting_payment_confirmation": "Still waiting for payment confirmation...",
            "payment_terminated": "Payment process terminated.",
            "specialization": "Specialization",
            "bio": "Bio",
            "not_set": "Not set",
            "no_doctors_found": "No doctors found",
            "no_hospitals_found": "No hospitals available yet",
            "reset_account_password": "Reset your account password",
            "whatsapp_phone_support": "Get WhatsApp or phone support",
            "submit_report": "Submit Report",
            "upload_photo": "Upload Photo",
            "age": "Age",
            "gender": "Gender",
            "send": "Send",
            "support_whatsapp": "WhatsApp Support",
            "system_metrics": "System Metrics",
            "free_demo_consultation_confirm": "This is a free demo consultation. No payment required. Do you want to continue?",
            "all_specialists": "All Specialists",
            "coming_soon_message": "We're working hard to bring this feature to you soon. Stay tuned for exciting updates!",
            "experience": "Experience",
            "refresh": "Refresh",
            "save": "Save",
            "saved": "Saved",
            "sort_by_experience": "Sort by Experience",
            "sort_by_name": "Sort by Name",
            "sort_by_rating": "Sort by Rating",
            "sounds_good": "Sounds Good",
            "ive_paid": "I've Paid",
            "terms_of_service": "Terms of Service",
            "terms_of_use": "Terms of Use",
            "terms_of_use_desc": "Protect your account now",
            "theme": "Theme",
            "today": "Today",
            "view_all": "View All",
            "view_doctor": "View Doctor",
            "view_profile": "View Profile",
            "no_pending_appointments": "No Pending Appointments",
            "all_caught_up": "You're all caught up! New appointments will appear here.",
            "filter_appointments": "Filter Appointments",
            "filter_appointments_by_status": "Show recent appointments by status.",
            "clear_filter": "Clear Filter",
            "edit_professional_info": "Edit Professional Info",
            "edit_professional_info_desc": "Change specialty, fee, etc.",
            "doctor_policy": "Doctor Policy",
            "doctor_policy_desc": "Information about Per service fee",
            "per_service_fee_policy": "Per Service Fee Policy",
            "per_service_fee_policy_body": "The per service fee is a fixed amount charged for each consultation or procedure performed. This fee covers the professional expertise of the doctor, use of facility equipment, and administrative costs.\n\nKey Points:\n1. The fee is non-refundable once the service is rendered.\n2. Emergency services may incur additional charges.\n3. Cancellation less than 2 hours before the appointment may result in a partial fee charge.\n4. Payments are processed securely via the AfyaHASET platform.",
            "location_tracking_access_policy": "Location Tracking & Access Policy",
            "location_tracking_policy_body": "To connect you with nearby patients and verify your clinic address, AfyaHASET requires access to your location.\n\nKey Points:\n1. Your precise location is only accessed when you actively add or update your clinic address.\n2. We do NOT track your location continuously in the background.\n3. Your clinic location is displayed to patients solely to help them navigate and book appointments with you.\n4. You can revoke location permissions at any time via your device settings, though this may limit your ability to update your clinic address.",
            "permanently_delete_your_account": "Permanently delete your account",
            "securely_log_out_of_account": "Securely log out of Account",
            "location_enabled": "Enabled",
            "location_disabled": "Disabled",
            "delete_account_confirm_title": "Delete account?",
            "delete_permanently": "Delete permanently",
            "delete_account_confirm_message": "Are you sure you want to delete your account? This action cannot be undone and all your data will be permanently deleted.",
            "notification_subtitle": "Appointment and account alerts",
            "my_wallet": "My Wallet",
            "wallet_statistics": "Wallet Statistics",
            "total_earnings": "Total Earnings",
            "withdrawal_history": "Withdrawal history",
            "transaction_history": "Transaction History",
            "no_withdrawals_yet": "No withdrawals yet.",
            "wallet_updated": "Updated",
            "wallet_unknown_date": "Unknown",
            "btn_withdraw": "Withdraw",
            "payout_accounts": "Payout accounts",
            "payout_accounts_desc": "Choose the account that should receive your payouts. Finance approval is required before use.",
            "checking_security": "Checking security…",
            "withdrawal_unavailable_title": "Withdrawal unavailable",
            "no_balance_withdrawal": "No balance is available for withdrawal.",
            "mfa_required_for_withdrawal_title": "Enable MFA to withdraw",
            "mfa_required_for_withdrawal_message": "Withdrawals require multi-factor authentication. Enable MFA first, then you may disable it later from Settings when you are not withdrawing.",
            "enable_mfa": "Enable MFA",
            "request_withdrawal": "Request withdrawal",
            "no_verified_payout_destination": "No approved payout account is available. Contact finance support.",
            "payout_account_label": "Payout account",
            "withdrawal_amount": "Amount",
            "submit": "Submit",
            "submitting": "Submitting…",
            "submit_for_approval": "Submit for approval",
            "payout_account_submitted_title": "Payout account submitted",
            "payout_account_submitted_message": "Finance approval and the security cooling-off period are required before withdrawal.",
            "enter_valid_withdrawal_amount": "Enter a valid amount within your available balance.",
            "enter_six_digit_mfa": "Enter the six-digit MFA code.",
            "invalid_phone_payout_format": "Use 07XXXXXXXX or +255XXXXXXXXX.",
            "authentication_expired": "Authentication expired. Please sign in again.",
            "provider_fee_format": "Provider fee: %@ TZS",
            "mobile_number": "Mobile number",
            "hide_balance": "Hide balance",
            "show_balance": "Show balance",
            "wallet_consultation_fees_info": "All consultation fees from completed appointments are automatically added to your wallet.",
            "processing": "Processing…",
            "retry": "Retry",
            "bank": "Bank",
            "ok": "OK",
            "welcome": "Welcome!",
            "welcome_desc": "Book doctors instantly and easily.",
            "connect_immediately": "Connect immediately with the doctor",
            "your_health_our_priority": "Your Health, Our Priority",
            "about_text_1": "AfyaHASET is a digital health app designed to make healthcare simple and accessible.",
            "about_text_2": "The app connects patients with qualified doctors for easy appointment booking, helps users find medicines in nearby pharmacies, and promotes health awareness through educational content and preventive care information.",
            "about_text_3": "Our goal is to improve healthcare access through technology and support healthier communities.",
            "about_disclaimer_body": "The information and services provided through AfyaHASET are intended for health management and educational purposes only. They do not substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health providers with any questions you may have regarding a medical condition. Do not disregard professional medical advice or delay in seeking it because of something you have read on this app.",
            "about": "About",
            "about_desc": "Learn more about the app",
            "childrens_corner": "Children's Corner",
            "contact_us": "Contact Us",
            "contact_us_desc": "Get in touch with support",
            "home_quote": "\"Afya ni mali yenye thamani kuliko fedha zote.\"",
            "home_quote_author": "— HASET Hospital",
            "professional_info": "Professional Information",
            "rate_app": "Rate App",
            "rate_app_desc": "Share your feedback on Play Store",
            "get_started": "Get Started",
            "theme_light": "Light",
            "theme_dark": "Dark",
            "theme_system": "System Default",
            "canceled": "Canceled",
            "declined": "Declined",
        ],
        "sw": [
            "app_name": "AfyaHASET",
            "tagline": "Huduma ya afya kiganja mwako",
            "about_us": "Kuhusu Sisi",
            "about_text_1": "AfyaHASET is a digital health app designed to make healthcare simple and accessible.",
            "about_text_2": "The app connects patients with qualified doctors for easy appointment booking, helps users find medicines in nearby pharmacies, and promotes health awareness through educational content and preventive care information.",
            "about_text_3": "Our goal is to improve healthcare access through technology and support healthier communities.",
            "about_disclaimer_body": "The information and services provided through AfyaHASET are intended for health management and educational purposes only. They do not substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health providers with any questions you may have regarding a medical condition. Do not disregard professional medical advice or delay in seeking it because of something you have read on this app.",
            "activity_logs": "Rekodi za Matukio",
            "additional": "Zaidi",
            "administrator": "Msimamizi",
            "administrator_dashboard": "Dashibodi ya Msimamizi",
            "all_users": "Watumiaji Wote",
            "already_have_account": "Tayari unayo akaunti?",
            "appointments": "Miadi",
            "book_online_chat": "Online Chat",
            "archived": "Kumbukumbu",
            "approved": "Imeidhinishwa",
            "approve": "Idhinisha",
            "articles": "Makala",
            "available": "Inapatikana",
            "available_times": "Muda Uliopo",
            "basic": "Msingi",
            "book_appointment": "Weka Miadi",
            "book_visit": "Weka Ziara",
            "booked": "Imejazwa",
            "bug_report": "Ripoti Hitilafu",
            "buy_medicine": "Nunua Dawa",
            "call_support": "Piga Huduma",
            "chat": "Soga",
            "chat_doctor": "Ongea na Daktari",
            "chat_securely": "Chat kwa Usalama",
            "chat_securely_desc": "Chat ya muda halisi na ujumbe wa faragha.",
            "close": "Funga",
            "cancel": "Ghairi",
            "cancel_payment": "Ghairi malipo",
            "cancel_payment_warning": "Malipo yako bado yanathibitishwa. Ghairi tu ikiwa hutaki kuendelea.",
            "keep_waiting": "Endelea kusubiri",
            "cancel_appointment": "Ghairi miadi",
            "completed": "Imekamilika",
            "contact": "Mawasiliano",
            "delete_account": "Futa Akaunti",
            "doctor": "Daktari",
            "doctor_dashboard": "Dashibodi ya Daktari",
            "doctor_details": "Taarifa za Daktari",
            "doctor_verified": "Imethibitishwa",
            "doctor_awaiting_admin_approval": "Akaunti yako inasubiri uidhinishaji wa msimamizi. Unaweza kutumia programu, lakini wagonjwa hawawezi kukupata au kukuwekea miadi hadi msimamizi athibitishe hati zako za MCT.",
            "doctor_pending_admin_badge": "Inasubiri idhini ya msimamizi",
            "error": "Hitilafu",
            "success": "Mafanikio",
            "login_failed": "Barua pepe au nenosiri si sahihi.",
            "registration_successful": "Usajili Umefanikiwa",
            "registration_failed": "Usajili Umeshindikana",
            "verify_email_after_registration": "Karibu HASET. Tafadhali angalia barua pepe yako na uthibitishe akaunti yako.",
            "verify_email_before_login": "Tafadhali thibitisha barua pepe yako kabla ya kuingia. Tumekutumia barua pepe mpya ya uthibitisho.",
            "reset_failed": "Kubadili Kumeshindikana",
            "update_failed": "Usasishaji Umeshindikana",
            "booking_successful": "Kuweka Miadi Kumefanikiwa",
            "booking_failed": "Kuweka Miadi Kumeshindikana",
            "report_sent": "Ripoti Imetumwa",
            "permission_required": "Ruhusa Inahitajika",
            "valid_email_required": "Tafadhali weka barua pepe sahihi",
            "password_too_short": "Nenosiri lazima liwe na angalau herufi 6",
            "strong_password_required": "Tumia angalau herufi 12 zenye herufi kubwa, ndogo na namba",
            "password_auth_ok": "Nenosiri linaonekana sahihi",
            "registration_fields_required": "Weka jina sahihi, barua pepe, namba ya simu ya tarakimu 9, na nenosiri lenye angalau herufi 12, herufi kubwa, ndogo na namba.",
            "verification_email_sent": "Barua pepe ya uthibitisho imetumwa. Angalia kikasha chako na folda ya barua taka, kisha uthibitishe akaunti yako kabla ya kuingia.",
            "name_required": "Tafadhali weka jina lako",
            "valid_phone_required": "Tafadhali weka namba sahihi ya simu",
            "mct_required": "Namba ya Usajili ya MCT inahitajika",
            "nin_required": "NIN inahitajika",
            "valid_nin_required": "Weka NIN sahihi ya tarakimu 20",
            "nin_document_required": "Pakia NIN yako kama PDF",
            "mct_certificate_required": "Pakia cheti cha usajili wa MCT kama PDF",
            "document_pdf_only": "Hati za PDF pekee ndizo zinakubalika",
            "upload_nin_document": "Pakia hati ya NIN (PDF)",
            "upload_mct_certificate": "Pakia cheti cha MCT (PDF)",
            "document_upload": "Pakia",
            "document_selected": "Imechaguliwa",
            "hint_mct_reg_no": "Namba ya Usajili ya Baraza la Madaktari Tanzania (MCT) (mf. MCT3625)",
            "hint_nin": "NIN (tarakimu 20)",
            "doctor_registration_pdf_details_required": "Weka maelezo sahihi na pakia hati zote mbili za uthibitishaji kama PDF.",
            "uploading_documents": "Inapakia nyaraka…",
            "doctor_reg_payment_required": "Lipa ada ya usajili wa daktari ili kumaliza kuingia. Huwezi kutumia programu hadi malipo yakamilike.",
            "login_locked": "Majiribio mengi ya kuingia yameshindwa. Tafadhali jaribu tena baada ya dakika %1$d.",
            "reset_email_sent": "Kiungo cha kubadilisha nenosiri kimetumwa kwenye barua pepe yako. Angalia kikasha chako na folda ya barua taka.",
            "reset_email_not_found": "Hakuna akaunti iliyosajiliwa kwa barua pepe hii. Angalia barua pepe au jisajili.",
            "profile_updated_successfully": "Wasifu umesasishwa kwa mafanikio",
            "describe_issue_first": "Tafadhali eleza tatizo kwanza",
            "report_recorded": "Ripoti yako imehifadhiwa kwa timu ya msaada ya HASET.",
            "select_date_required": "Tafadhali chagua tarehe",
            "select_time_required": "Tafadhali chagua muda",
            "chat_booking_success": "Miadi imewekwa kwa mafanikio",
            "appointment_booking_success": "Miadi imewekwa kwa mafanikio",
            "notifications_permission_message": "AfyaHASET inahitaji ruhusa ya arifa kukutumia vikumbusho muhimu vya miadi na ujumbe wa karibu. Tafadhali wezesha arifa katika mipangilio.",
            "location_permission_message": "Tafadhali ruhusu upatikanaji wa mahali kwenye mipangilio ya iPhone ili kutumia hospitali za karibu na kutafuta madaktari.",
            "choose_appointment_type": "Choose Appointment Type",
            "dont_have_account": "Hauna akaunti?",
            "change_password": "Badili Nenosiri",
            "edit_profile": "Hariri Wasifu",
            "email": "Barua Pepe",
            "english": "Kiingereza",
            "find_doctors": "Tafuta Madaktari",
            "find_hospital": "Tafuta Hospitali",
            "filter_by_specialist": "Chuja kwa Utaalamu",
            "forgot_password": "Umesahau Nenosiri?",
            "forgot_password_description": "Weka barua pepe yako na tutakutumia kiungo cha kubadilisha nenosiri lako.",
            "full_name": "Jina Kamili",
            "general": "Jumla",
            "health_at_hand": "AfyaHASET",
            "health_at_hand_desc": "Fuatilia miadi na maelezo ya dawa.",
            "help_support": "Msaada na Usaidizi",
            "home": "Nyumbani",
            "hospitals": "Hospitali",
            "hello": "Habari,",
            "im_administrator": "Mimi ni Msimamizi",
            "im_doctor": "Mimi ni Daktari",
            "im_patient": "Mimi ni Mgonjwa",
            "inbox": "Kikasha",
            "instant_appointment": "Instant Appointment",
            "kiswahili": "Kiswahili",
            "language": "Lugha",
            "location": "Mahali",
            "location_permission": "Ufikiaji wa Mahali",
            "login": "Ingia",
            "logout": "Toka",
            "manage_schedule": "Simamia Ratiba",
            "medical_disclaimer": "Medical Disclaimer",
            "medical_records": "Rekodi za Matibabu",
            "more": "Zaidi",
            "my_appointments": "Miadi Yangu",
            "my_prescriptions": "Maagizo Yangu",
            "patients": "Wagonjwa",
            "filter": "Chuja",
            "no_prescriptions_message": "Maelekezo yako yataonekana hapa",
            "prescriptions": "Maagizo ya Dawa",
            "passwords_do_not_match": "Nywila hazilingani",
            "password_reset_success": "Nenosiri limebadilishwa. Tafadhali ingia tena.",
            "paste_reset_link": "Weka kiungo cha kubadilisha nenosiri",
            "reset_new_password": "Nenosiri Mpya",
            "reset_confirm_password": "Thibitisha Nenosiri Mpya",
            "reset_password_action": "Badilisha Nenosiri",
            "no_appointments_message": "Hakuna miadi iliyopatikana",
            "no_messages_message": "Hakuna ujumbe bado",
            "next": "Inayofuata",
            "nearby_hospitals": "Hospitali za Karibu",
            "notification": "Arifa",
            "notifications": "Arifa",
            "or": "au",
            "password": "Nenosiri",
            "patient": "Mgonjwa",
            "patient_dashboard": "Dashibodi ya Mgonjwa",
            "payment": "Malipo",
            "secure_payment": "Malipo Salama",
            "payment_initiated": "Malipo yameanzishwa. Tafadhali kamilisha muamala kwenye simu yako.",
            "preparing_payment": "Inashughulikia malipo…",
            "payment_session_unavailable": "Malipo salama hayako tayari. Bonyeza Lipa Sasa kujaribu tena.",
            "payment_method": "Njia ya Malipo",
            "payment_number": "Namba ya Wallet",
            "payment_provider": "Mtoa Huduma",
            "pay_now": "Lipa Sasa",
            "pending": "Inasubiri",
            "decline": "Kataa",
            "reschedule": "Panga upya",
            "reschedule_appointment": "Panga miadi upya",
            "start_chat": "Anza Mazungumzo Sasa",
            "open_chat": "Ongea Sasa",
            "confirm_appointment_action": "Una uhakika unataka kubadilisha miadi hii?",
            "phone": "Namba ya Simu",
            "phone_number": "Namba ya Simu",
            "popular_articles": "Makala Maarufu",
            "popular_doctors": "Madaktari Maarufu",
            "preferences": "Mapendeleo",
            "privacy_policy": "Sera ya Faragha",
            "profile": "Wasifu",
            "published": "Imechapishwa",
            "quick_access": "Njia za Haraka",
            "recent": "Karibuni",
            "recent_appointments": "Miadi za Karibuni",
            "register": "Jisajili",
            "remember_me": "Nikumbuke",
            "remember_password": "Unakumbuka nenosiri?",
            "role_selection_title": "Chagua Jukumu Lako",
            "save_changes": "Hifadhi Mabadiliko",
            "schedule_appointment": "Panga Miadi",
            "schedule_for_future": "Book for a future date and time",
            "select_method": "Chagua njia",
            "select_provider": "Chagua mtoa huduma",
            "schedule_overview": "Muhtasari wa Leo",
            "today_s_overview": "Muhtasari wa Leo",
            "quick_actions": "Vitendo vya Haraka & Huduma",
            "schedule": "Ratiba",
            "search": "Tafuta",
            "check_status": "Angalia Hali",
            "select_date": "Chagua Tarehe",
            "select_time": "Chagua Muda",
            "services": "Huduma",
            "send_reset_link": "Tuma Kiungo cha Kuweka Upya",
            "settings": "Mipangilio",
            "multi_factor_authentication": "Uthibitishaji wa hatua mbili",
            "mfa_enabled_desc": "Ulinzi wa ziada wa kuingia umewashwa",
            "mfa_disabled_desc": "Linda kuingia kwa programu ya uthibitishaji",
            "reason_for_visit": "Sababu ya ziara",
            "share_profile": "Shiriki Wasifu",
            "sign_in": "Ingia",
            "sign_in_here": "Jisajili hapa",
            "sign_up": "Jisajili",
            "status": "Hali",
            "support": "Msaada",
            "search_articles": "Tafuta makala...",
            "search_doctors": "Tafuta daktari",
            "health_tips": "Vidokezo vya Afya",
            "no_health_tips_found": "Hakuna vidokezo vya afya vilivyopatikana",
            "no_articles_found": "Hakuna makala zilizopatikana",
            "no_comments_yet": "Hakuna maoni bado",
            "write_comment": "Andika maoni...",
            "post_comment": "Tuma Maoni",
            "comments": "Maoni",
            "use_date": "Tumia Tarehe",
            "use_time": "Tumia Muda",
            "consultation_fee": "Ada ya ushauri",
            "payment_method_label": "Njia ya malipo",
            "mobile_money": "Pesa ya simu",
            "card_payment": "Kadi / Benki",
            "hosted_card_checkout": "Ukurasa salama wa malipo ya kadi",
            "card_checkout_description": "Utakamilisha malipo kwenye ukurasa salama wa mtoa huduma. HASET haihifadhi taarifa za kadi.",
            "card_checkout_opened": "Ukurasa salama wa kadi umefunguliwa",
            "account_card_number": "Namba ya akaunti / kadi",
            "terminate": "Sitisha",
            "payment_in_progress": "Malipo yanaendelea",
            "confirm_prompt_phone": "Tafadhali angalia simu yako kwa ujumbe wa USSD",
            "waiting_payment_confirmation": "Inasubiri uthibitisho wa malipo...",
            "check_phone_complete_payment": "Angalia simu yako ukamilishe malipo.",
            "payment_confirmed": "Malipo yamethibitishwa kwa mafanikio!",
            "still_waiting_payment_confirmation": "Bado inasubiri uthibitisho wa malipo...",
            "payment_terminated": "Mchakato wa malipo umesitishwa.",
            "specialization": "Utaalamu",
            "bio": "Maelezo",
            "not_set": "Haijawekwa",
            "no_doctors_found": "Hakuna madaktari waliopatikana",
            "no_hospitals_found": "Bado hakuna hospitali zilizowekwa",
            "reset_account_password": "Badili nenosiri la akaunti yako",
            "whatsapp_phone_support": "Pata msaada wa WhatsApp au simu",
            "submit_report": "Tuma Ripoti",
            "upload_photo": "Pakia Picha",
            "age": "Umri",
            "gender": "Jinsia",
            "send": "Tuma",
            "support_whatsapp": "Msaada wa WhatsApp",
            "system_metrics": "Takwimu za Mfumo",
            "free_demo_consultation_confirm": "Huu ni ushauri wa majaribio bila malipo. Malipo hayahitajiki. Unataka kuendelea?",
            "all_specialists": "Utaalamu Wote",
            "coming_soon_message": "We're working hard to bring this feature to you soon. Stay tuned for exciting updates!",
            "experience": "Uzoefu",
            "refresh": "Onyesha Upya",
            "save": "Hifadhi",
            "saved": "Imehifadhiwa",
            "sort_by_experience": "Panga kwa Uzoefu",
            "sort_by_name": "Panga kwa Jina",
            "sort_by_rating": "Panga kwa Kiwango",
            "sounds_good": "Sounds Good",
            "ive_paid": "Nimeshalipa",
            "terms_of_service": "Terms of Service",
            "terms_of_use": "Masharti ya Matumizi",
            "terms_of_use_desc": "Linda akaunti yako sasa",
            "theme": "Mandhari",
            "today": "Leo",
            "view_all": "Angalia Zote",
            "view_doctor": "Tazama Daktari",
            "view_profile": "Tazama Wasifu",
            "no_pending_appointments": "Hakuna Miadi Inayosubiri",
            "all_caught_up": "Umekamilisha! Miadi mipya itaonekana hapa.",
            "filter_appointments": "Chuja Miadi",
            "filter_appointments_by_status": "Onyesha miadi za hivi karibuni kwa hali.",
            "clear_filter": "Futa Kichujio",
            "edit_professional_info": "Hariri Taarifa za Kitaaluma",
            "edit_professional_info_desc": "Badilisha utaalamu, ada, n.k.",
            "doctor_policy": "Sera ya Daktari",
            "doctor_policy_desc": "Taarifa kuhusu ada ya kila huduma",
            "per_service_fee_policy": "Sera ya Ada kwa Kila Huduma",
            "per_service_fee_policy_body": "Ada kwa kila huduma ni kiasi kisichobadilika kinachotozwa kwa kila ushauri au huduma inayofanyika. Ada hii inalipia utaalamu wa daktari, matumizi ya vifaa vya kituo, na gharama za usimamizi.\n\nMambo Muhimu:\n1. Ada hairudishwi baada ya huduma kutolewa.\n2. Huduma za dharura zinaweza kuwa na gharama za ziada.\n3. Kughairi chini ya saa 2 kabla ya miadi kunaweza kusababisha kutozwa sehemu ya ada.\n4. Malipo huchakatwa kwa usalama kupitia app ya AfyaHASET.",
            "location_tracking_access_policy": "Sera ya Ufuatiliaji na Ruhusa ya Eneo",
            "location_tracking_policy_body": "Ili kukuunganisha na wagonjwa walio karibu na kuthibitisha anwani ya kliniki yako, AfyaHASET inahitaji ruhusa ya eneo lako.\n\nMambo Muhimu:\n1. Eneo lako sahihi hutumika tu unapoongeza au kusasisha anwani ya kliniki yako.\n2. Hatufuatilii eneo lako muda wote kwa nyuma.\n3. Eneo la kliniki yako huonyeshwa kwa wagonjwa ili kuwasaidia kufika na kuweka miadi.\n4. Unaweza kuondoa ruhusa ya eneo wakati wowote kupitia mipangilio ya kifaa chako, ingawa hii inaweza kupunguza uwezo wako wa kusasisha anwani ya kliniki.",
            "permanently_delete_your_account": "Futa akaunti yako kabisa",
            "securely_log_out_of_account": "Ondoka kwenye akaunti yako kwa usalama",
            "location_enabled": "Imewashwa",
            "location_disabled": "Imezimwa",
            "delete_account_confirm_title": "Futa akaunti?",
            "delete_permanently": "Futa kabisa",
            "delete_account_confirm_message": "Je, una uhakika unataka kufuta akaunti yako? Hatua hii haiwezi kutenguliwa na data zako zote zitafutwa kabisa.",
            "notification_subtitle": "Arifa za miadi na akaunti",
            "my_wallet": "Waleti Yangu",
            "wallet_statistics": "Takwimu za Waleti",
            "total_earnings": "Jumla ya Mapato",
            "withdrawal_history": "Historia ya kutoa pesa",
            "transaction_history": "Historia ya Malipo",
            "no_withdrawals_yet": "Hakuna malipo yaliyotolewa bado.",
            "wallet_updated": "Imesasishwa",
            "wallet_unknown_date": "Haijulikani",
            "btn_withdraw": "Toa Pesa",
            "payout_accounts": "Akaunti za Malipo",
            "payout_accounts_desc": "Chagua akaunti itakayopokea malipo yako. Idhini ya fedha inahitajika kabla ya kuitumia.",
            "checking_security": "Inakagua usalama…",
            "withdrawal_unavailable_title": "Kutoa pesa hakupatikani",
            "no_balance_withdrawal": "Hakuna salio la kutoa.",
            "mfa_required_for_withdrawal_title": "Washa MFA ili kutoa pesa",
            "mfa_required_for_withdrawal_message": "Kutoa pesa kunahitaji uthibitishaji wa hatua nyingi. Washa MFA kwanza; unaweza kuizima baadaye kwenye Mipangilio wakati hautoi pesa.",
            "enable_mfa": "Washa MFA",
            "request_withdrawal": "Omba kutoa pesa",
            "no_verified_payout_destination": "Hakuna akaunti ya malipo iliyoidhinishwa. Wasiliana na msaada wa fedha.",
            "payout_account_label": "Akaunti ya malipo",
            "withdrawal_amount": "Kiasi",
            "submit": "Wasilisha",
            "submitting": "Inawasilisha…",
            "submit_for_approval": "Wasilisha kwa idhini",
            "payout_account_submitted_title": "Akaunti ya malipo imewasilishwa",
            "payout_account_submitted_message": "Idhini ya fedha na kipindi cha ulinzi wa usalama vinahitajika kabla ya kutoa pesa.",
            "enter_valid_withdrawal_amount": "Weka kiasi halali ndani ya salio lako linalopatikana.",
            "enter_six_digit_mfa": "Weka msimbo wa MFA wa tarakimu sita.",
            "invalid_phone_payout_format": "Tumia 07XXXXXXXX au +255XXXXXXXXX.",
            "authentication_expired": "Uthibitishaji umeisha. Tafadhali ingia tena.",
            "provider_fee_format": "Ada ya mtoa huduma: %@ TZS",
            "mobile_number": "Namba ya simu",
            "hide_balance": "Ficha salio",
            "show_balance": "Onyesha salio",
            "wallet_consultation_fees_info": "Ada zote za ushauri kutoka kwa miadi iliyokamilika huongezwa kwenye waleti yako kiotomatiki.",
            "processing": "Inashughulikia…",
            "retry": "Jaribu Tena",
            "bank": "Benki",
            "ok": "Sawa",
            "welcome": "Karibu!",
            "welcome_desc": "Weka miadi na madaktari papo hapo na kwa urahisi.",
            "connect_immediately": "Connect immediately with the doctor",
            "your_health_our_priority": "Afya Yako, Kipaumbele Chetu",
            "about": "Kuhusu",
            "about_desc": "Jifunze zaidi kuhusu programu",
            "childrens_corner": "Kona ya Watoto",
            "contact_us": "Wasiliana Nasi",
            "contact_us_desc": "Wasiliana na msaada",
            "home_quote": "\"Afya ni mali yenye thamani kuliko fedha zote.\"",
            "home_quote_author": "— Hospitali ya HASET",
            "professional_info": "Taarifa za Kitaaluma",
            "rate_app": "Kadiria Programu",
            "rate_app_desc": "Shiriki maoni yako kwenye Play Store",
            "get_started": "Anza Sasa",
            "theme_light": "Mwanga",
            "theme_dark": "Giza",
            "theme_system": "Chaguo-msingi la Mfumo",
            "canceled": "Imeghairiwa",
            "declined": "Imekataliwa",
        ]
    ]

    static func tr(_ key: String, languageCode: String) -> String {
        strings[languageCode]?[key] ?? strings["en"]?[key] ?? key
    }
}

extension UserRole {
    func localizedDisplayName(languageCode: String) -> String {
        switch self {
        case .patient:
            return L10n.tr("patient", languageCode: languageCode)
        case .doctor:
            return L10n.tr("doctor", languageCode: languageCode)
        case .admin:
            return L10n.tr("administrator", languageCode: languageCode)
        }
    }
}

extension ThemeMode {
    func localizedLabel(languageCode: String) -> String {
        switch self {
        case .light:
            return L10n.tr("theme_light", languageCode: languageCode)
        case .dark:
            return L10n.tr("theme_dark", languageCode: languageCode)
        case .system:
            return L10n.tr("theme_system", languageCode: languageCode)
        }
    }
}

extension AppointmentSummary.Status {
    func localizedLabel(languageCode: String) -> String {
        switch self {
        case .pending:
            return L10n.tr("pending", languageCode: languageCode)
        case .approved:
            return L10n.tr("approved", languageCode: languageCode)
        case .completed:
            return L10n.tr("completed", languageCode: languageCode)
        case .cancelled:
            return L10n.tr("canceled", languageCode: languageCode)
        case .declined:
            return L10n.tr("declined", languageCode: languageCode)
        }
    }
}
