import Foundation

enum L10n {
    private static let strings: [String: [String: String]] = [
        "en": [
            "about_us": "About Us",
            "activity_logs": "Activity Logs",
            "additional": "Additional",
            "administrator": "Administrator",
            "administrator_dashboard": "Administrator Dashboard",
            "all_users": "All Users",
            "already_have_account": "Already have an account?",
            "appointments": "Appointments",
            "book_online_chat": "Book Online Chat",
            "archived": "Archived",
            "approved": "Approved",
            "articles": "Articles",
            "available": "Available",
            "available_times": "Available Times",
            "basic": "Basic",
            "book_appointment": "Book Appointment",
            "book_visit": "Book Visit",
            "booked": "Booked",
            "bug_report": "Bug Report",
            "buy_medicine": "Buy Medicine",
            "call_support": "Call Support",
            "chat": "Chat",
            "chat_doctor": "Chat Doctor",
            "chat_securely": "Chat Securely",
            "chat_securely_desc": "Real-time chat and private messaging.",
            "close": "Close",
            "completed": "Completed",
            "contact": "Contact",
            "delete_account": "Delete Account",
            "doctor": "Doctor",
            "doctor_dashboard": "Doctor Dashboard",
            "doctor_details": "Doctor Details",
            "doctor_verified": "Verified",
            "error": "Error",
            "success": "Success",
            "login_failed": "Login Failed",
            "registration_successful": "Registration Successful",
            "registration_failed": "Registration Failed",
            "reset_failed": "Reset Failed",
            "update_failed": "Update Failed",
            "booking_successful": "Booking Successful",
            "booking_failed": "Booking Failed",
            "report_sent": "Report Sent",
            "permission_required": "Permission Required",
            "valid_email_required": "Please enter a valid email",
            "password_too_short": "Password must be at least 6 characters",
            "strong_password_required": "Use at least 12 characters with uppercase, lowercase, and a number.",
            "name_required": "Please enter your name",
            "valid_phone_required": "Please enter a valid phone number",
            "mct_required": "Tanzanian Medical Council (MCT) Reg. No. is required",
            "reset_email_sent": "Reset email sent",
            "profile_updated_successfully": "Profile updated successfully",
            "describe_issue_first": "Please describe the issue first",
            "report_recorded": "Your report has been recorded for the HASET support team.",
            "select_date_required": "Please select a date",
            "select_time_required": "Please select a time",
            "chat_booking_success": "Your chat appointment is booked. Please wait for doctor approval.",
            "appointment_booking_success": "Your appointment has been booked successfully. Please wait for doctor approval.",
            "notifications_permission_message": "Please allow notifications in iPhone Settings to receive appointment and account updates.",
            "location_permission_message": "Please allow location access in iPhone Settings to use nearby hospitals and doctor discovery.",
            "choose_appointment_type": "Choose Appointment Type",
            "dont_have_account": "Don't have an account?",
            "change_password": "Change Password",
            "edit_profile": "Edit Profile",
            "email": "Email",
            "english": "English",
            "find_doctors": "Find Doctors",
            "find_hospital": "Find Hospital",
            "filter_by_specialist": "Filter by Specialist",
            "forgot_password": "Forgot Password?",
            "forgot_password_description": "Enter your email address and we'll send you a link to reset your password.",
            "full_name": "Full Name",
            "general": "General",
            "health_at_hand": "Health at Hand",
            "health_at_hand_desc": "Track appointments & prescriptions.",
            "help_support": "Help & Support",
            "home": "Home",
            "hospitals": "Hospitals",
            "hello": "Hello",
            "im_administrator": "I'm an Administrator",
            "im_doctor": "I'm a Doctor",
            "im_patient": "I'm a Patient",
            "inbox": "Inbox",
            "instant_appointment": "Instant Appointment",
            "kiswahili": "Kiswahili",
            "language": "Language",
            "location": "Location",
            "location_permission": "Location Permission",
            "login": "Login",
            "logout": "Logout",
            "manage_schedule": "Manage Schedule",
            "medical_disclaimer": "Medical Disclaimer",
            "medical_records": "Medical Records",
            "more": "More",
            "my_appointments": "My Appointments",
            "my_prescriptions": "My Prescriptions",
            "patients": "Patients",
            "filter": "Filter",
            "no_prescriptions_message": "No prescriptions available yet",
            "no_appointments_message": "No appointments found",
            "no_messages_message": "No messages found",
            "next": "Next",
            "nearby_hospitals": "Nearby Hospitals",
            "notification": "Notification",
            "notifications": "Notifications",
            "or": "or",
            "password": "Password",
            "patient": "Patient",
            "patient_dashboard": "Patient Dashboard",
            "payment": "Payment",
            "payment_initiated": "Payment initiated. Complete the prompt on your phone, then check status.",
            "payment_method": "Payment Method",
            "payment_number": "Wallet Number",
            "payment_provider": "Provider",
            "pay_now": "Pay Now",
            "pending": "Pending",
            "phone": "Phone",
            "phone_number": "Phone Number",
            "popular_articles": "Popular Articles",
            "popular_doctors": "Popular Doctors",
            "preferences": "Preferences",
            "privacy_policy": "Privacy Policy",
            "profile": "Profile",
            "published": "Published",
            "quick_access": "Quick Access",
            "recent": "Recent",
            "recent_appointments": "Recent Appointments",
            "register": "Register",
            "remember_me": "Remember me",
            "remember_password": "Remember your password?",
            "role_selection_title": "Select Your Role",
            "save_changes": "Save Changes",
            "schedule_appointment": "Schedule Appointment",
            "schedule_for_future": "Book for a future date and time",
            "select_method": "Select method",
            "select_provider": "Select provider",
            "schedule_overview": "Today's Overview",
            "today_s_overview": "Today's Overview",
            "quick_actions": "Quick Actions",
            "schedule": "Schedule",
            "search": "Search",
            "check_status": "Check Status",
            "select_date": "Select Date",
            "select_time": "Select Time",
            "services": "Services",
            "send_reset_link": "Send Reset Link",
            "settings": "Settings",
            "reason_for_visit": "Reason for visit",
            "share_profile": "Share Profile",
            "sign_in": "Sign In",
            "sign_in_here": "Sign Up here",
            "sign_up": "Sign Up",
            "status": "Status",
            "support": "Support",
            "search_articles": "Search articles...",
            "search_doctors": "Search doctors",
            "health_tips": "Health Tips",
            "no_articles_found": "No articles found",
            "no_comments_yet": "No comments yet",
            "write_comment": "Write a comment...",
            "post_comment": "Post Comment",
            "comments": "Comments",
            "use_date": "Use Date",
            "use_time": "Use Time",
            "consultation_fee": "Consultation Fee",
            "payment_method_label": "Payment method",
            "mobile_money": "Mobile Money",
            "card_payment": "Card Payment",
            "hosted_card_checkout": "Secure hosted card checkout",
            "card_checkout_description": "You will complete payment on the secure gateway page. HASET never collects card details.",
            "card_checkout_opened": "Secure card checkout opened",
            "account_card_number": "Account / card number",
            "terminate": "Terminate",
            "payment_in_progress": "Payment in progress",
            "confirm_prompt_phone": "Please confirm the request on your phone.",
            "waiting_payment_confirmation": "Waiting for payment confirmation...",
            "check_phone_complete_payment": "Check your phone to complete the payment.",
            "payment_confirmed": "Payment confirmed.",
            "still_waiting_payment_confirmation": "Still waiting for payment confirmation...",
            "payment_terminated": "Payment process terminated.",
            "specialization": "Specialization",
            "bio": "Bio",
            "not_set": "Not provided",
            "no_doctors_found": "No doctors found",
            "no_hospitals_found": "No hospitals available yet",
            "reset_account_password": "Reset your account password",
            "whatsapp_phone_support": "Get WhatsApp or phone support",
            "submit_report": "Submit Report",
            "upload_photo": "Upload Photo",
            "age": "Age",
            "gender": "Gender",
            "send": "Send",
            "support_whatsapp": "WhatsApp Support",
            "system_metrics": "System Metrics",
            "use_demo_free_booking": "This consultation is free. Continue without payment?",
            "all_specialists": "All Specialists",
            "coming_soon_message": "We're working hard to bring this feature to you soon. Stay tuned for exciting updates!",
            "experience": "Experience",
            "refresh": "Refresh",
            "save": "Save",
            "saved": "Saved",
            "sort_by_experience": "Sort by Experience",
            "sort_by_name": "Sort by Name",
            "sort_by_rating": "Sort by Rating",
            "sounds_good": "Sounds Good",
            "ive_paid": "I've Paid",
            "terms_of_service": "Terms of Service",
            "terms_of_use": "Terms of Use",
            "terms_of_use_desc": "Review the usage terms of the app",
            "theme": "Theme",
            "today": "Today",
            "view_all": "View All",
            "view_doctor": "View Doctor",
            "view_profile": "View Profile",
            "welcome": "Welcome!",
            "welcome_desc": "Book doctors instantly and easily.",
            "connect_immediately": "Connect immediately with the doctor",
            "your_health_our_priority": "Your Health, Our Priority",
            "about_text_1": "HASET is a digital health app designed to make healthcare simple and accessible.",
            "about_text_2": "The app connects patients with qualified doctors for easy appointment booking, helps users find medicines in nearby pharmacies, and promotes health awareness through educational content and preventive care information.",
            "about_text_3": "Our goal is to improve healthcare access through technology and support healthier communities.",
            "about_disclaimer_body": "The information and services provided through HASET are intended for health management and educational purposes only. They do not substitute for professional medical advice, diagnosis, or treatment.",
            "about": "About",
            "about_desc": "Learn more about the app",
            "childrens_corner": "Children's Corner",
            "contact_us": "Contact Us",
            "contact_us_desc": "Get in touch with support",
            "home_quote": "\"Health is wealth beyond money.\"",
            "home_quote_author": "HASET Hospital",
            "professional_info": "Professional Information",
            "rate_app": "Rate App",
            "rate_app_desc": "Share your feedback about the app"
        ],
        "sw": [
            "about_us": "Kuhusu Sisi",
            "about_text_1": "HASET ni programu ya afya ya kidijitali iliyoundwa kufanya huduma za afya ziwe rahisi na zifikiwe kwa urahisi.",
            "about_text_2": "Programu inaunganisha wagonjwa na madaktari wenye sifa kwa urahisi wa kuweka miadi, kusaidia kupata dawa katika maduka ya karibu, na kuhamasisha elimu ya afya kupitia maudhui ya kielimu na kinga.",
            "about_text_3": "Lengo letu ni kuboresha upatikanaji wa huduma za afya kwa kutumia teknolojia na kusaidia jamii zenye afya.",
            "about_disclaimer_body": "Taarifa na huduma zinazotolewa kupitia HASET ni kwa usimamizi wa afya na elimu tu. Haziwezi kuchukua nafasi ya ushauri, uchunguzi, au matibabu ya kitaalamu.",
            "activity_logs": "Rekodi za Matukio",
            "additional": "Zaidi",
            "administrator": "Msimamizi",
            "administrator_dashboard": "Dashibodi ya Msimamizi",
            "all_users": "Watumiaji Wote",
            "already_have_account": "Tayari una akaunti?",
            "appointments": "Miadi",
            "book_online_chat": "Weka Soga la Mtandaoni",
            "archived": "Kumbukumbu",
            "approved": "Imeidhinishwa",
            "articles": "Makala",
            "available": "Inapatikana",
            "available_times": "Muda Uliopo",
            "basic": "Msingi",
            "book_appointment": "Weka Miadi",
            "book_visit": "Weka Ziara",
            "booked": "Imejazwa",
            "bug_report": "Ripoti Hitilafu",
            "buy_medicine": "Nunua Dawa",
            "call_support": "Piga Huduma",
            "chat": "Soga",
            "chat_doctor": "Soga na Daktari",
            "chat_securely": "Soga Kwa Usalama",
            "chat_securely_desc": "Mazungumzo ya moja kwa moja na ujumbe binafsi.",
            "close": "Funga",
            "completed": "Imekamilika",
            "contact": "Mawasiliano",
            "delete_account": "Futa Akaunti",
            "doctor": "Daktari",
            "doctor_dashboard": "Dashibodi ya Daktari",
            "doctor_details": "Taarifa za Daktari",
            "doctor_verified": "Imethibitishwa",
            "error": "Hitilafu",
            "success": "Mafanikio",
            "login_failed": "Kuingia Kimeshindikana",
            "registration_successful": "Usajili Umefanikiwa",
            "registration_failed": "Usajili Umeshindikana",
            "reset_failed": "Kubadili Kumeshindikana",
            "update_failed": "Usasishaji Umeshindikana",
            "booking_successful": "Kuweka Miadi Kumefanikiwa",
            "booking_failed": "Kuweka Miadi Kumeshindikana",
            "report_sent": "Ripoti Imetumwa",
            "permission_required": "Ruhusa Inahitajika",
            "valid_email_required": "Tafadhali weka barua pepe sahihi",
            "password_too_short": "Nenosiri lazima liwe na angalau herufi 6",
            "strong_password_required": "Tumia angalau herufi 12 zenye herufi kubwa, ndogo na namba.",
            "name_required": "Tafadhali weka jina lako",
            "valid_phone_required": "Tafadhali weka namba sahihi ya simu",
            "mct_required": "Namba ya usajili ya Baraza la Madaktari Tanzania (MCT) inahitajika",
            "reset_email_sent": "Barua pepe ya kubadili nenosiri imetumwa",
            "profile_updated_successfully": "Wasifu umesasishwa kwa mafanikio",
            "describe_issue_first": "Tafadhali eleza tatizo kwanza",
            "report_recorded": "Ripoti yako imehifadhiwa kwa timu ya msaada ya HASET.",
            "select_date_required": "Tafadhali chagua tarehe",
            "select_time_required": "Tafadhali chagua muda",
            "chat_booking_success": "Miadi ya soga imewekwa. Tafadhali subiri idhini ya daktari.",
            "appointment_booking_success": "Miadi yako imewekwa kwa mafanikio. Tafadhali subiri idhini ya daktari.",
            "notifications_permission_message": "Tafadhali ruhusu arifa kwenye mipangilio ya iPhone ili upokee masasisho ya miadi na akaunti.",
            "location_permission_message": "Tafadhali ruhusu upatikanaji wa mahali kwenye mipangilio ya iPhone ili kutumia hospitali za karibu na kutafuta madaktari.",
            "choose_appointment_type": "Chagua Aina ya Miadi",
            "dont_have_account": "Huna akaunti?",
            "change_password": "Badili Nenosiri",
            "edit_profile": "Hariri Wasifu",
            "email": "Barua Pepe",
            "english": "Kiingereza",
            "find_doctors": "Tafuta Madaktari",
            "find_hospital": "Tafuta Hospitali",
            "filter_by_specialist": "Chuja kwa Utaalamu",
            "forgot_password": "Umesahau Nenosiri?",
            "forgot_password_description": "Weka barua pepe yako tukutumie kiungo cha kubadili nenosiri.",
            "full_name": "Jina Kamili",
            "general": "Jumla",
            "health_at_hand": "Afya Mkoni",
            "health_at_hand_desc": "Fuatilia miadi na madawa.",
            "help_support": "Msaada",
            "home": "Nyumbani",
            "hospitals": "Hospitali",
            "hello": "Habari",
            "im_administrator": "Mimi ni Msimamizi",
            "im_doctor": "Mimi ni Daktari",
            "im_patient": "Mimi ni Mgonjwa",
            "inbox": "Kikasha",
            "instant_appointment": "Miadi ya Haraka",
            "kiswahili": "Kiswahili",
            "language": "Lugha",
            "location": "Mahali",
            "location_permission": "Ruhusa ya Mahali",
            "login": "Ingia",
            "logout": "Toka",
            "manage_schedule": "Simamia Ratiba",
            "medical_disclaimer": "Tahadhari ya Kitabibu",
            "medical_records": "Rekodi za Matibabu",
            "more": "Zaidi",
            "my_appointments": "Miadi Yangu",
            "my_prescriptions": "Maagizo Yangu",
            "patients": "Wagonjwa",
            "filter": "Chuja",
            "no_prescriptions_message": "Bado hakuna maagizo ya dawa",
            "no_appointments_message": "Hakuna miadi iliyopatikana",
            "no_messages_message": "Hakuna ujumbe uliopatikana",
            "next": "Endelea",
            "nearby_hospitals": "Hospitali za Karibu",
            "notification": "Arifa",
            "notifications": "Arifa",
            "or": "au",
            "password": "Nenosiri",
            "patient": "Mgonjwa",
            "patient_dashboard": "Dashibodi ya Mgonjwa",
            "payment": "Malipo",
            "payment_initiated": "Malipo yameanzishwa. Kamilisha uthibitisho kwenye simu yako kisha angalia hali.",
            "payment_method": "Njia ya Malipo",
            "payment_number": "Namba ya Wallet",
            "payment_provider": "Mtoa Huduma",
            "pay_now": "Lipa Sasa",
            "pending": "Inasubiri",
            "phone": "Simu",
            "phone_number": "Namba ya Simu",
            "popular_articles": "Makala Maarufu",
            "popular_doctors": "Madaktari Maarufu",
            "preferences": "Mapendeleo",
            "privacy_policy": "Sera ya Faragha",
            "profile": "Wasifu",
            "published": "Imechapishwa",
            "quick_access": "Njia za Haraka",
            "recent": "Karibuni",
            "recent_appointments": "Miadi za Karibuni",
            "register": "Jisajili",
            "remember_me": "Nikumbuke",
            "remember_password": "Unakumbuka nenosiri?",
            "role_selection_title": "Chagua Jukumu Lako",
            "save_changes": "Hifadhi Mabadiliko",
            "schedule_appointment": "Panga Miadi",
            "schedule_for_future": "Weka kwa tarehe na muda wa baadaye",
            "select_method": "Chagua njia",
            "select_provider": "Chagua mtoa huduma",
            "schedule_overview": "Muhtasari wa Leo",
            "today_s_overview": "Muhtasari wa Leo",
            "quick_actions": "Vitendo vya Haraka",
            "schedule": "Ratiba",
            "search": "Tafuta",
            "check_status": "Angalia Hali",
            "select_date": "Chagua Tarehe",
            "select_time": "Chagua Muda",
            "services": "Huduma",
            "send_reset_link": "Tuma Kiungo",
            "settings": "Mipangilio",
            "reason_for_visit": "Sababu ya ziara",
            "share_profile": "Shiriki Wasifu",
            "sign_in": "Ingia",
            "sign_in_here": "Jisajili hapa",
            "sign_up": "Jisajili",
            "status": "Hali",
            "support": "Msaada",
            "search_articles": "Tafuta makala...",
            "search_doctors": "Tafuta daktari",
            "health_tips": "Vidokezo vya Afya",
            "no_articles_found": "Hakuna makala zilizopatikana",
            "no_comments_yet": "Hakuna maoni bado",
            "write_comment": "Andika maoni...",
            "post_comment": "Tuma Maoni",
            "comments": "Maoni",
            "use_date": "Tumia Tarehe",
            "use_time": "Tumia Muda",
            "consultation_fee": "Ada ya ushauri",
            "payment_method_label": "Njia ya malipo",
            "mobile_money": "Pesa ya simu",
            "card_payment": "Kadi / Benki",
            "hosted_card_checkout": "Ukurasa salama wa malipo ya kadi",
            "card_checkout_description": "Utakamilisha malipo kwenye ukurasa salama wa mtoa huduma. HASET haihifadhi taarifa za kadi.",
            "card_checkout_opened": "Ukurasa salama wa kadi umefunguliwa",
            "account_card_number": "Namba ya akaunti / kadi",
            "terminate": "Sitisha",
            "payment_in_progress": "Malipo yanaendelea",
            "confirm_prompt_phone": "Tafadhali thibitisha ombi kwenye simu yako.",
            "waiting_payment_confirmation": "Inasubiri uthibitisho wa malipo...",
            "check_phone_complete_payment": "Angalia simu yako ukamilishe malipo.",
            "payment_confirmed": "Malipo yamethibitishwa.",
            "still_waiting_payment_confirmation": "Bado inasubiri uthibitisho wa malipo...",
            "payment_terminated": "Mchakato wa malipo umesitishwa.",
            "specialization": "Utaalamu",
            "bio": "Maelezo",
            "not_set": "Haijatolewa",
            "no_doctors_found": "Hakuna madaktari waliopatikana",
            "no_hospitals_found": "Bado hakuna hospitali zilizowekwa",
            "reset_account_password": "Badili nenosiri la akaunti yako",
            "whatsapp_phone_support": "Pata msaada wa WhatsApp au simu",
            "submit_report": "Tuma Ripoti",
            "upload_photo": "Pakia Picha",
            "age": "Umri",
            "gender": "Jinsia",
            "send": "Tuma",
            "support_whatsapp": "Msaada wa WhatsApp",
            "system_metrics": "Takwimu za Mfumo",
            "use_demo_free_booking": "Huduma hii ni bure. Endelea bila malipo?",
            "all_specialists": "Utaalamu Wote",
            "coming_soon_message": "Tunafanyia kazi kipengele hiki kikufikie hivi karibuni. Endelea kufuatilia masasisho mapya.",
            "experience": "Uzoefu",
            "refresh": "Onyesha Upya",
            "save": "Hifadhi",
            "saved": "Imehifadhiwa",
            "sort_by_experience": "Panga kwa Uzoefu",
            "sort_by_name": "Panga kwa Jina",
            "sort_by_rating": "Panga kwa Kiwango",
            "sounds_good": "Sawa",
            "ive_paid": "Nimelipa",
            "terms_of_service": "Masharti ya Huduma",
            "terms_of_use": "Masharti ya Matumizi",
            "terms_of_use_desc": "Kagua masharti ya matumizi ya programu",
            "theme": "Mandhari",
            "today": "Leo",
            "view_all": "Tazama Zote",
            "view_doctor": "Tazama Daktari",
            "view_profile": "Tazama Wasifu",
            "welcome": "Karibu!",
            "welcome_desc": "Weka miadi ya daktari kwa urahisi.",
            "connect_immediately": "Unganishwa mara moja na daktari",
            "your_health_our_priority": "Afya Yako, Kipaumbele Chetu",
            "about": "Kuhusu",
            "about_desc": "Jifunze zaidi kuhusu programu",
            "childrens_corner": "Kona ya Watoto",
            "contact_us": "Wasiliana Nasi",
            "contact_us_desc": "Pata msaada kutoka kwa timu",
            "home_quote": "\"Afya ni mali yenye thamani kuliko fedha zote.\"",
            "home_quote_author": "Hospitali ya HASET",
            "professional_info": "Taarifa za Kitaaluma",
            "rate_app": "Kadiria Programu",
            "rate_app_desc": "Toa maoni yako kuhusu programu"
        ]
    ]

    static func tr(_ key: String, languageCode: String) -> String {
        strings[languageCode]?[key] ?? strings["en"]?[key] ?? key
    }
}

extension UserRole {
    func localizedDisplayName(languageCode: String) -> String {
        switch self {
        case .patient:
            return L10n.tr("patient", languageCode: languageCode)
        case .doctor:
            return L10n.tr("doctor", languageCode: languageCode)
        case .admin:
            return L10n.tr("administrator", languageCode: languageCode)
        }
    }
}

extension ThemeMode {
    func localizedLabel(languageCode: String) -> String {
        switch self {
        case .light:
            return languageCode == "sw" ? "Mwanga" : "Light"
        case .dark:
            return languageCode == "sw" ? "Giza" : "Dark"
        case .system:
            return languageCode == "sw" ? "Mfumo" : "System"
        }
    }
}

extension AppointmentSummary.Status {
    func localizedLabel(languageCode: String) -> String {
        switch self {
        case .pending:
            return L10n.tr("pending", languageCode: languageCode)
        case .approved:
            return L10n.tr("approved", languageCode: languageCode)
        case .completed:
            return L10n.tr("completed", languageCode: languageCode)
        case .cancelled:
            return languageCode == "sw" ? "Imeghairiwa" : "Canceled"
        }
    }
}
